### ISSUE TITLE
Regression in 1.2.14: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by gverm** [aylton-almeida/rabbitmq-pika-flask#19]
@pedrooa It seems your latest commit broke non-dead-lettered queues, reverting back to 1.2.13 fixes it.

RabbitMQ.py:279 [ERROR] ERROR IN basic.start.index: 'NoneType' object has no attribute 'get'

**Comment by pedrooa** [comment]
Thanks for reporting this @gverm ! MR fixing this issue opened and will be available in version 1.2.15
