### ISSUE TITLE
message_id is no longer a required positional argument for queues

### ISSUE THREAD

**Issue by gverm** [aylton-almeida/rabbitmq-pika-flask#28]
@aylton-almeida

As of https://github.com/aylton-almeida/rabbitmq-pika-flask/commit/af6ab788b2ba4049b6aefa11be5db7f2d8b17f15 I get an error that queue is missing positional argument 'message_id'.

Would it be possible to keep this automatically generated if it's not provided?

**Comment by gverm** [comment]
My initial thoughts about this were wrong. The problem is that message_id is no longer a required positional argument for queues. I've opened #38 to fix this in the case where props_needed is not provided.

**Comment by rafaelclp** [comment]
Fix released on 1.2.25.
