### ISSUE TITLE
Provide pre-built wheel

### ISSUE THREAD

**Issue by gverm** [aylton-almeida/rabbitmq-pika-flask#29]
Currently, when installing this package with pip, setup.py is used or a wheel gets built if package 'wheel' is installed. Since you're already pushing releases to PyPi, it should be pretty easy to add the pre-built wheels. I've used [this tutorial](https://realpython.com/pypi-publish-python-package/#publish-your-package-to-pypi) successfully in the past.

**Comment by rafaelclp** [comment]
Pre-built wheel now provided starting from 1.2.26
