### ISSUE TITLE
Setting Virtual Host

### ISSUE THREAD

**Issue by adback03** [aylton-almeida/rabbitmq-pika-flask#6]
Would it be possible to support setting the `virtual_host` when creating the connection? Here is the relevant code:

```
self.get_connection = lambda: BlockingConnection(ConnectionParameters(
      host=os.getenv('MQ_HOST'),
      port=os.getenv('MQ_PORT'),
      credentials=PlainCredentials(
          username=os.getenv('MQ_USER'),
          password=os.getenv('MQ_PASS')
      ),
      ssl_options=SSLOptions(ssl.SSLContext(
          ssl.PROTOCOL_TLSv1_2)) if use_ssl else None,
      heartbeat=300,
      blocked_connection_timeout=150
  ))
```

`virtual_host` is a supported connection parameter from pika.

Alternatively, it could be nice to support all connection parameters via a single connection string:

```
params = URLParameters(self.config['MQ_URL'])
self.get_connection = lambda: BlockingConnection(params)
```

Also, should the `os.getenv` calls be updated to use the app.config from flask? Like `app.config['MQ_HOST']`.

Thanks!

**Comment by aylton-almeida** [comment]
Could you open a Pull Request for it? It really is a significant improvement, but I will only have time to look at it during the weekend
